[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'

remappings = [
  'solmate=lib/solmate/src',
  'oz-upgradeable=lib/openzeppelin-contracts-upgradeable/',
  'oz-regular=lib/openzeppelin-contracts/',
  '@xerc20=lib/xerc20/solidity',
]
